#!/usr/bin/env python3
"""
Convert a CSV (rows produced by `generate_adt_csv.py`) into HL7 v2.5.1 ADT messages.

For each row the script will assemble MSH, EVN, PID, PV1 and optional DG1/IN1/NK1 segments
using columns present in the CSV. It writes all messages to a single output file
separated by a blank line. Field separator is `|` and component separator is `^`.
"""

import argparse
import pandas as pd
import uuid
from datetime import datetime


def fmt_ts(val):
    # Accept either YYYYMMDDHHMMSS or date-like; ensure HL7 TS format
    if pd.isna(val) or val == "":
        return ""
    s = str(val)
    # If already seems like YYYYMMDD..., return trimmed
    if s.isdigit() and len(s) >= 8:
        return s[:14].ljust(14, '0')
    # Otherwise try parse
    for fmt in ("%Y-%m-%d", "%Y-%m-%d %H:%M:%S", "%Y%m%d"):
        try:
            dt = datetime.strptime(s, fmt)
            return dt.strftime("%Y%m%d%H%M%S")
        except Exception:
            continue
    return s


def make_msh(row):
    field_sep = '|'
    enc = '^~\\&'
    sending_app = row.get('msh-3') or row.get('sendingapplication') or 'SYNTH_APP'
    sending_fac = row.get('msh-4') or row.get('sendingfacility') or 'SYNTH_FAC'
    recv_app = row.get('msh-5') or row.get('receivingapplication') or 'REC_APP'
    recv_fac = row.get('msh-6') or row.get('receivingfacility') or 'REC_FAC'
    ts = fmt_ts(row.get('msh-7')) or datetime.utcnow().strftime("%Y%m%d%H%M%S")
    msg_type = row.get('msh-9') or 'ADT^A04'
    ctrl = row.get('msh-10') or uuid.uuid4().hex
    proc = row.get('msh-11') or 'P'
    ver = row.get('msh-12') or '2.5.1'
    parts = ["MSH", field_sep + enc, sending_app, sending_fac, recv_app, recv_fac, ts, '', msg_type, ctrl, proc, ver]
    return field_sep.join(parts)


def make_evn(row):
    evn1 = row.get('evn-1') or row.get('eventtype') or 'A04'
    evn2 = fmt_ts(row.get('evn-2')) or datetime.utcnow().strftime("%Y%m%d%H%M%S")
    return f"EVN|{evn1}|{evn2}"


def make_pid(row):
    # PID-3 is commonly the patient identifier list; accept full value or numeric
    pid3 = row.get('subject_id') or row.get('pid-3') or ''
    name = row.get('pid-5') or row.get('patientname') or ''
    dob = fmt_ts(row.get('pid-7') or row.get('dob') or row.get('birth') or '')
    sex = row.get('gender') or row.get('sex') or ''
    race = row.get('race') or ''
    addr = row.get('pid-11') or row.get('address') or ''
    phone = row.get('pid-13') or row.get('phone') or ''
    ethnic = row.get('ethnicity') or row.get('pid-22') or ''
    parts = ["PID", "1", "", pid3, "", name, dob, sex, race, "", addr, phone, "", "", "", "", "", "", ethnic]
    return '|'.join(parts)


def make_pv1(row):
    pclass = row.get('pv1-2') or row.get('patientclass') or row.get('admissiontype') or 'O'
    assigned = row.get('pv1-3') or row.get('assignedlocation') or ''
    attending = row.get('pv1-7') or row.get('attending') or ''
    service = row.get('pv1-10') or row.get('hospitalservice') or ''
    visitnum = row.get('pv1-19') or row.get('hadm_id') or ''
    admit = fmt_ts(row.get('pv1-44') or row.get('admittime') or '')
    disc = fmt_ts(row.get('pv1-45') or row.get('dischtime') or row.get('dischargedatetime') or '')
    parts = ["PV1", "1", pclass, assigned, "", "", attending, "", "", service, "", "", "", "", "", "", "", "", "", visitnum, "", "", "", "", "", "", "", "", "", "", "", "", "", admit, disc]
    return '|'.join(parts)


def make_dg1(row):
    code = row.get('diagnosiscode') or row.get('dg1') or ''
    desc = row.get('diagnosis') or row.get('dxdesc') or ''
    if not code:
        return ''
    # If code already contains ^ then use it, else build CE
    if '^' in code:
        ce = code
    else:
        ce = f"{code}^{desc}^ICD-10"
    return f"DG1|1||{ce}||"


def make_in1(row):
    in1 = row.get('in1') or row.get('insurance') or ''
    if not in1:
        return ''
    return f"IN1|1|{in1}"


def make_nk1(row):
    nk = row.get('nk1') or row.get('nextofkin') or ''
    if not nk:
        return ''
    return f"NK1|1|{nk}"


def row_to_message(row):
    # row is a pandas Series; coerce to dict-like get
    r = {k: (v if pd.notna(v) else '') for k, v in row.items()}
    segs = []
    segs.append(make_msh(r))
    segs.append(make_evn(r))
    segs.append(make_pid(r))
    pv1 = make_pv1(r)
    if pv1:
        segs.append(pv1)
    dg1 = make_dg1(r)
    if dg1:
        segs.append(dg1)
    in1 = make_in1(r)
    if in1:
        segs.append(in1)
    nk1 = make_nk1(r)
    if nk1:
        segs.append(nk1)
    # HL7 segments should be terminated by CR (\r)
    msg = '\r'.join(segs) + '\r'
    return msg


def main():
    parser = argparse.ArgumentParser(description="Convert CSV rows to HL7 ADT messages.")
    parser.add_argument('--csv', type=str, required=True, help='Input CSV file generated by generate_adt_csv.py')
    parser.add_argument('--out', type=str, default='generated_hl7_messages.hl7', help='Output HL7 file to write')
    args = parser.parse_args()

    df = pd.read_csv(args.csv, dtype=str)
    messages = []
    for _, row in df.iterrows():
        messages.append(row_to_message(row))

    with open(args.out, 'w', encoding='utf-8', newline='') as f:
        # Write each message separated by a single blank line
        for msg in messages:
            f.write(msg)
            f.write('\n')

    print(f" Wrote {len(messages)} HL7 messages → {args.out}")


if __name__ == '__main__':
    main()
